baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'aim high'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: ''

seo:
  meta_og_title: "VitCamp"
  meta_og_type: "website"
  meta_og_url: "https://vitcamp.com"
  meta_og_description: "IT Service and Outsourcing"
  meta_twitter_card: "summary"
  meta_twitter_site: "@vitcamp"
  meta_twitter_creator: "@vitcamp"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
